// This file is generated by apc_parsers.py do not edit!

#pragma once

#include "base64.h"

static inline void parse_audio_code(PS *self, uint8_t *parser_buf,
                                    const size_t parser_buf_pos) {
  unsigned int pos = 1;
  size_t payload_start = 0;
  enum PARSER_STATES {
    KEY,
    EQUAL,
    UINT,
    INT,
    FLAG,
    SKIP,
    AFTER_VALUE,
    PAYLOAD
  };
  enum PARSER_STATES state = KEY, value_state = FLAG;
  AudioCommand g = {0};
  g.has_preroll = false;
  g.has_autoplay = false;
  g.has_loop_count = false;
  g.has_volume = false;
  g.has_seek = false;
  unsigned int i, code;
  uint64_t lcode;
  int64_t accumulator;
  bool is_negative;
  (void)is_negative;
  size_t sz;

  enum KEYS {
    action = 'a',
    id = 'i',
    format = 's',
    rate = 'r',
    channels = 'c',
    more = 'm',
    transmission_type = 't',
    data_sz = 'S',
    data_offset = 'O',
    timestamp = 'T',
    preroll = 'B',
    autoplay = 'P',
    loop_count = 'L',
    playback_state = 'p',
    volume = 'v',
    seek = 'k',
    quiet = 'q'
  };

  enum KEYS key = 'a';
  if (parser_buf[pos] == ';')
    state = AFTER_VALUE;

  while (pos < parser_buf_pos) {
    switch (state) {
    case KEY:
      key = parser_buf[pos++];
      state = EQUAL;
      switch (key) {
      case action:
        value_state = FLAG;
        break;
      case id:
        value_state = UINT;
        break;
      case format:
        value_state = SKIP;
        break;
      case rate:
        value_state = UINT;
        break;
      case channels:
        value_state = UINT;
        break;
      case more:
        value_state = UINT;
        break;
      case transmission_type:
        value_state = FLAG;
        break;
      case data_sz:
        value_state = UINT;
        break;
      case data_offset:
        value_state = UINT;
        break;
      case timestamp:
        value_state = UINT;
        break;
      case preroll:
        value_state = UINT;
        break;
      case autoplay:
        value_state = UINT;
        break;
      case loop_count:
        value_state = UINT;
        break;
      case playback_state:
        value_state = UINT;
        break;
      case volume:
        value_state = UINT;
        break;
      case seek:
        value_state = UINT;
        break;
      case quiet:
        value_state = UINT;
        break;
      default:
        REPORT_ERROR(
            "Malformed AudioCommand control block, invalid key character: 0x%x",
            key);
        return;
      }
      break;

    case EQUAL:
      if (parser_buf[pos++] != '=') {
        REPORT_ERROR("Malformed AudioCommand control block, no = after key, "
                     "found: 0x%x instead",
                     parser_buf[pos - 1]);
        return;
      }
      state = value_state;
      break;

    case FLAG:
      switch (key) {

      case action: {
        g.action = parser_buf[pos++];
        if (g.action != 'd' && g.action != 'p' && g.action != 'q' &&
            g.action != 't') {
          REPORT_ERROR("Malformed AudioCommand control block, unknown flag "
                       "value for action: 0x%x",
                       g.action);
          return;
        };
      } break;

      case transmission_type: {
        g.transmission_type = parser_buf[pos++];
        if (g.transmission_type != 'd' && g.transmission_type != 'f' &&
            g.transmission_type != 's' && g.transmission_type != 't') {
          REPORT_ERROR("Malformed AudioCommand control block, unknown flag "
                       "value for transmission_type: 0x%x",
                       g.transmission_type);
          return;
        };
      } break;

      default:
        break;
      }
      state = AFTER_VALUE;
      break;

    case INT:
#define READ_UINT                                                              \
  for (i = pos, accumulator = 0; i < MIN(parser_buf_pos, pos + 10); i++) {     \
    int64_t n = parser_buf[i] - '0';                                           \
    if (n < 0 || n > 9)                                                        \
      break;                                                                   \
    accumulator += n * digit_multipliers[i - pos];                             \
  }                                                                            \
  if (i == pos) {                                                              \
    REPORT_ERROR("Malformed AudioCommand control block, expecting an integer " \
                 "value for key: %c",                                          \
                 key & 0xFF);                                                  \
    return;                                                                    \
  }                                                                            \
  lcode = accumulator / digit_multipliers[i - pos - 1];                        \
  pos = i;                                                                     \
  if (lcode > UINT32_MAX) {                                                    \
    REPORT_ERROR("Malformed AudioCommand control block, number is too large"); \
    return;                                                                    \
  }                                                                            \
  code = lcode;

      is_negative = false;
      if (parser_buf[pos] == '-') {
        is_negative = true;
        pos++;
      }
#define I(x)                                                                   \
  case x:                                                                      \
    g.x = is_negative ? 0 - (int32_t)code : (int32_t)code;                     \
    break
      READ_UINT;
      switch (key) {
        ;
      default:
        break;
      }
      state = AFTER_VALUE;
      break;
#undef I
    case UINT:
      READ_UINT;
#define U(x)                                                                   \
  case x:                                                                      \
    g.x = code;                                                                \
    break
      switch (key) {
      case id:
        g.id = code;
        break;
        ;
      case rate:
        g.rate = code;
        break;
        ;
      case channels:
        g.channels = code;
        break;
        ;
      case more:
        g.more = code;
        break;
        ;
      case data_sz:
        g.data_sz = code;
        break;
        ;
      case data_offset:
        g.data_offset = code;
        break;
        ;
      case timestamp:
        g.timestamp = code;
        break;
        ;
      case preroll:
        g.preroll = code;
        g.has_preroll = true;
        break;
        ;
      case autoplay:
        g.autoplay = code;
        g.has_autoplay = true;
        break;
        ;
      case loop_count:
        g.loop_count = code;
        g.has_loop_count = true;
        break;
        ;
      case playback_state:
        g.playback_state = code;
        g.has_playback_state = true;
        break;
        ;
      case volume:
        g.volume = code;
        g.has_volume = true;
        break;
        ;
      case seek:
        g.seek = code;
        g.has_seek = true;
        break;
        ;
      case quiet:
        g.quiet = code;
        break;
        ;
      default:
        break;
      }
      state = AFTER_VALUE;
      break;
#undef U
#undef READ_UINT

    case SKIP:
      // Skip value until we hit ',' or ';'
      while (pos < parser_buf_pos && parser_buf[pos] != ',' &&
             parser_buf[pos] != ';') {
        pos += 1;
      }
      state = AFTER_VALUE;
      break;

    case AFTER_VALUE:
      switch (parser_buf[pos++]) {
      default:
        REPORT_ERROR("Malformed AudioCommand control block, expecting a , or "
                     "semi-colon after a value, found: 0x%x",
                     parser_buf[pos - 1]);
        return;
      case ',':
        state = KEY;
        break;
      case ';':
        state = PAYLOAD;
        break;
      }
      break;

    case PAYLOAD: {
      sz = parser_buf_pos - pos;
      payload_start = pos;
      g.payload_sz = sz;
      pos = parser_buf_pos;
    } break;

    } // end switch
  } // end while

  switch (state) {
  case EQUAL:
    REPORT_ERROR("Malformed AudioCommand control block, no = after key");
    return;
  case INT:
  case UINT:
    REPORT_ERROR(
        "Malformed AudioCommand control block, expecting an integer value");
    return;
  case FLAG:
    REPORT_ERROR(
        "Malformed AudioCommand control block, expecting a flag value");
    return;
  default:
    break;
  }

  REPORT_VA_COMMAND(
      "K s {sc sc sI sI sI sI sI sI sI sI sI sI sI sI sI sI  ss#}",
      self->window_id, "audio_command",

      "action", g.action, "transmission_type", g.transmission_type,

      "id", (unsigned int)g.id, "rate", (unsigned int)g.rate, "channels",
      (unsigned int)g.channels, "more", (unsigned int)g.more, "data_sz",
      (unsigned int)g.data_sz, "data_offset", (unsigned int)g.data_offset,
      "timestamp", (unsigned int)g.timestamp, "preroll",
      (unsigned int)g.preroll, "autoplay", (unsigned int)g.autoplay,
      "loop_count", (unsigned int)g.loop_count, "playback_state",
      (unsigned int)g.playback_state, "volume", (unsigned int)g.volume, "seek",
      (unsigned int)g.seek, "quiet", (unsigned int)g.quiet,

      "", (char *)parser_buf + payload_start, g.payload_sz);

  audio_extract_format(parser_buf, parser_buf_pos, g.format, sizeof(g.format));
  screen_handle_audio_command(self->screen, &g, parser_buf + payload_start);
}
